services:
  api:
    container_name: couchdb-nestjs-api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '2000:2000'
    env_file:
      - .env
    volumes:
      - .:/app
